package com.example.wallpaper20

var list = arrayListOf(
    "Home",
    "Tree",
    "mountains",
    "sea",
    "car",
    "sky",
    "animal",
)

val shayariMap = mapOf(
    "Tree" to arrayListOf(
        R.drawable.fonl2,
        R.drawable.pan3,
        R.drawable.tree3,
        R.drawable.pan,
        R.drawable.pan2,
        R.drawable.three,
        R.drawable.three2,
        R.drawable.threy,
        R.drawable.tree2,
        R.drawable.tree1,
        R.drawable.tree4,
        R.drawable.tree5,
    ),
    "mountains" to arrayListOf(
        R.drawable.digan,
        R.drawable.ful,
        R.drawable.logo1,
        R.drawable.paevat,
        R.drawable.parvat,
        R.drawable.mountains1,
        R.drawable.mountains2,
        R.drawable.mountains3,
        R.drawable.mountains4,
        R.drawable.mountains5,
        R.drawable.mountains6,
        R.drawable.mountains7,
        R.drawable.mountains8,
        R.drawable.mountains9,
        R.drawable.mountains10,
        R.drawable.mountains11,
        R.drawable.mountains12,
        R.drawable.mountains13,
        R.drawable.mountains14,
        R.drawable.mountains15,
        R.drawable.mountains16,
        R.drawable.mountains17,
        R.drawable.mountains18,
        R.drawable.mountains19,
        R.drawable.mountains20,
        R.drawable.mountains21,
        R.drawable.mountains23,
    ),
    "sea" to arrayListOf(
        R.drawable.lalten,
        R.drawable.navadiandsee,
        R.drawable.navdi,
        R.drawable.sea1,
        R.drawable.sea2,
        R.drawable.sea3,
        R.drawable.sea4,
        R.drawable.sea5,
        R.drawable.sea6,
        R.drawable.sea7,
        R.drawable.sea8,
        R.drawable.sea9,
        R.drawable.sea10,
    ),
    "car" to arrayListOf(
        R.drawable.bol,
        R.drawable.cars1,
        R.drawable.cars3,
        R.drawable.jali,
        R.drawable.modil,
        R.drawable.rod,
        R.drawable.rod2,
        R.drawable.trans,
        R.drawable.rod3,
        R.drawable.rod1,
    ),
    "sky" to arrayListOf(
        R.drawable.airrplan,
        R.drawable.arora,
        R.drawable.badals,
        R.drawable.bilding,
        R.drawable.city,
        R.drawable.snaset,
        R.drawable.sunfols,
        R.drawable.whitfonl,
        R.drawable.winds,
        R.drawable.sky1,
        R.drawable.sky2,
        R.drawable.sky3,
        R.drawable.sky4,
        R.drawable.sky5,
        R.drawable.sky6,
        R.drawable.sky7,
        R.drawable.sky8,
    ),
    "animal" to arrayListOf(
        R.drawable.blacklogo,
        R.drawable.cat,
        R.drawable.elefans,
        R.drawable.foxs,
        R.drawable.gidh,
        R.drawable.monkey,
        R.drawable.hathi,
        R.drawable.kabutar,
        R.drawable.newpopat,
        R.drawable.pandas,
        R.drawable.tgars,
        R.drawable.vadh,
        R.drawable.ziraf,
        ),
)
